 -*- coding: utf-8 -*-
"""generar_grafico_hosteleria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSqpfwig0s_tquwbOOq5pDZ416S2uhqh
"""

import matplotlib.pyplot as plt
import numpy as np

# Configuración de estilo visual profesional
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 5.5), dpi=300)

# Paleta de colores (Branding IAnnuzzi Data / Tech)
color_primary = '#1E3A8A'  # Azul oscuro
color_secondary = '#0D9488' # Verde azulado / Teal
color_accent = '#E11D48'    # Rojo / Rosa acentuado
color_bg = '#F8FAFC'

fig.patch.set_facecolor(color_bg)

# ---------------------------------------------------------
# PANEL 1: Tiempo Medio de Permanencia en Mesa (Minutos)
# ---------------------------------------------------------
formatos = ['Tradicional\n(Servicio Completo)', 'Casual Dining\n(Actual)', 'Fast Casual\n(Tech & Low Cost)']
tiempos = [85, 55, 38]

bars1 = ax1.bar(formatos, tiempos, color=[color_primary, color_secondary, color_accent], width=0.55)
ax1.set_title('Tiempo Medio en Mesa (Turn Time)', fontsize=13, fontweight='bold', pad=15)
ax1.set_ylabel('Minutos por comensal', fontsize=11)
ax1.set_ylim(0, 100)

# Añadir valores sobre las barras
for bar in bars1:
    yval = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2, yval + 2, f'{yval} min', ha='center', va='bottom', fontweight='bold', fontsize=10)

# ---------------------------------------------------------
# PANEL 2: Distribución y Tendencia del Ticket Medio (€)
# ---------------------------------------------------------
categorias = ['Gama Media\n(Tradicional)', 'Fast Casual /\nQSR (Low Cost)', 'Alta Cocina\n(Experiencial)']
ticket_medio = [32, 14, 85]
tendencia = [-18, +25, +8] # Cambio porcentual simulado de demanda

x = np.arange(len(categorias))
width = 0.4

bars2 = ax2.bar(x, ticket_medio, width, color=color_primary, alpha=0.85)
ax2.set_title('Ticket Medio por Comensal (€)', fontsize=13, fontweight='bold', pad=15)
ax2.set_ylabel('Euros (€)', fontsize=11)
ax2.set_xticks(x)
ax2.set_xticklabels(categorias)
ax2.set_ylim(0, 100)

for bar in bars2:
    yval = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2, yval + 2, f'{yval}€', ha='center', va='bottom', fontweight='bold', fontsize=10)

# ---------------------------------------------------------
# PANEL 3: Rotación de Mesas por Turno (Table Turnover)
# ---------------------------------------------------------
rotacion = [1.2, 1.8, 2.7]

bars3 = ax3.bar(formatos, rotacion, color=[color_primary, color_secondary, color_accent], width=0.55)
ax3.set_title('Rotación de Mesas por Turno', fontsize=13, fontweight='bold', pad=15)
ax3.set_ylabel('Turnos / Cierres por mesa', fontsize=11)
ax3.set_ylim(0, 3.5)

for bar in bars3:
    yval = bar.get_height()
    ax3.text(bar.get_x() + bar.get_width()/2, yval + 0.08, f'{yval}x', ha='center', va='bottom', fontweight='bold', fontsize=10)

# ---------------------------------------------------------
# Ajustes finales y título global
# ---------------------------------------------------------
plt.suptitle('Transformación Operativa en Hostelería: Velocidad vs. Servicio Tradicional',
             fontsize=16, fontweight='bold', y=1.03, color='#0F172A')

# Limpiar bordes innecesarios
for ax in [ax1, ax2, ax3]:
    ax.set_facecolor(color_bg)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()

# Guardar la imagen en alta calidad
plt.savefig('hosteleria_tendencias_infographic.png', dpi=300, bbox_inches='tight')
print("¡Infografía generada con éxito como 'hosteleria_tendencias_infographic.png'!")
plt.show()
